default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: myapp_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: myapp_test
  username: postgres
  password: postgres

production:
  primary:
    <<: *default
    database: myapp_primary_production
    username: deployer
    password: Bhopal*1!asa

  cable:
    <<: *default
    database: myapp_cable_production
    username: deployer
    password: Bhopal*1!asa

  queue:
    <<: *default
    database: myapp_queue_production
    username: deployer
    password: Bhopal*1!asa

  cache:
    <<: *default
    database: myapp_cache_production
    username: deployer
    password: Bhopal*1!asa
